### ISSUE TITLE
Provide usage documentation for using jsc-android without react native

### ISSUE THREAD

**Issue by jaladankisuresh** [SoftwareMansion/jsc-android-buildscripts#10]
I am just starting with Android NDK, and i am trying to run JavaScriptCore Engine inside Android dalvik VM.
Can i use this build with Android NDK, without using react native? If Yes, can you help with the instructions

Thank you

**Comment by ukasiu** [comment]
Hi @jaladankisuresh,
yes, you can use this build without using React Native. Unfortunately we don't have enough resources to provide you with exact instructions -- you may try to see how React Native does it and you may also find this useful https://stackoverflow.com/a/12238575
