### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by ragamufin** [SoftwareMansion/jsc-android-buildscripts#11]
A quick question as I couldn't find it in the docs but does this support Proxies? Are you running code using them without any issues?

**Comment by ukasiu** [comment]
Seems it does. This compilation should support more or less the same as Safari 10.1. Also I've tested few examples from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy and they worked.

**Comment by ragamufin** [comment]
thanks!
