### ISSUE TITLE
How to build the library with source-level debug information?

### ISSUE THREAD

**Issue by anql** [SoftwareMansion/jsc-android-buildscripts#22]
I found a crash on release version and want to use "arm-linux-androideabi-addr2line" to check the source code. How to build the library with source-level debug information? 
Not good at english, wish this is clear. Thanks!

**Comment by ukasiu** [comment]
@anql Please tell if this helps: https://github.com/SoftwareMansion/jsc-android-buildscripts/issues/13#issuecomment-331090615

**Comment by anql** [comment]
@ukasiu It works! 
Thank you very much!
