### ISSUE TITLE
timeline for project

### ISSUE THREAD

**Issue by hey99xx** [SoftwareMansion/jsc-android-buildscripts#7]
First of all, I appreciate the effort put in this by Expo and Software Mansion engineers.

I wanted to ask the future plans for this repo. Do you intend to replace android-jsc at any point? In other words, are you collaborating with FB devs to make this (the smaller, non-intl variant) the standard JavaScript engine on React Native Android, without requiring the patches? 

If so, is there a timeline set, such as a certain version of React Native will start using this project? If not, why not?

Also, an unrelated question. Your project description states:

> Script for building JavaScriptCore for Android (for React Native **but not only**)

How does this "not only" part work? As far as I see you're creating .so files, not a Java library. So if I'd like to use this as a standalone JavaScript engine one day, do you expect me to write C++ code for the integration? This part can require quite an expertise, as I imagine most JavaScript and/or Android devs are not familiar with C++ in their daily work (me included).

**Comment by ide** [comment]
From the Expo side, we're looking into including the newer version of JSC with Expo clients in the future and all Expo developers (including if you detach) will just get the new JSC without any changes needed.

**Comment by hey99xx** [comment]
Then, I assume there's no plan yet to merge back to Facebook react-native's repository, i.e. make them switch from android-jsc to this package.

Are you at any point declare the project stable for other to consume, or is it too risk for now? I see you might still have bugs to figure out, since you have an open issue "Linking errors on Android 4.4".

**Comment by kmagiera** [comment]
@hey99xx as for the "but not only" statement we've put it there as I can imagine other projects related to react native can benefit from this. This project does not have any dependencies on react native and allows you to use jsc shared library on android with its standard bindings (that is c/c++). We do not plan on providing any wrappers that would allow for using libjsc directly from java/kotlin code as this is outside of the scope of this project. There are also so many ways on how such a binding could be build, and the choice has to be made based on the usecase.

Regarding the question about switching RN to use JSC build with this project our focus now is to ship this with the most recent Expo distribution. Once that's done and if we don't see any issues related to this change we will start the discussion on how and when to update RN with the most recent JSC.

**Comment by hey99xx** [comment]
Sounds reasonable. Thanks for addressing both my comments.
